# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "59c7dbfbeefd1f11ba1aa85228d3700a"
name = "Volume discount"
handle = "volume-discount-63"
application_url = "https://jm-disclose-introduce-contribution.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zinza002.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://jm-disclose-introduce-contribution.trycloudflare.com/auth/callback",
  "https://jm-disclose-introduce-contribution.trycloudflare.com/auth/shopify/callback",
  "https://jm-disclose-introduce-contribution.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
