# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "59c7dbfbeefd1f11ba1aa85228d3700a"
name = "Simple Discount"
handle = "sd-xxyy"
application_url = "https://retro-workers-syndication-lost.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zinza002.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_discounts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://retro-workers-syndication-lost.trycloudflare.com/auth/callback",
  "https://retro-workers-syndication-lost.trycloudflare.com/auth/shopify/callback",
  "https://retro-workers-syndication-lost.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "discounts/create",
  "discounts/delete",
  "discounts/update"
]
  uri = "pubsub://earnest-command-226202:vd_discount"

[pos]
embedded = false
