api_version = "2024-07"

[[extensions]]
name = "Volume Discount"
description = "Buy more, discount more"
handle = "vd"
type = "function"

[[extensions.targeting]]
target = "purchase.product-discount.run"
input_query = "src/run.graphql"
export = "run"

[extensions.input.variables]
namespace = "$app:pd"
key = "pd_config"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/dcs/create/volume"
details = "/app/dcs/:id"
