api_version = "2024-07"

[[extensions]]
name = "Shipping discount"
handle = "sd"
type = "function"

description = ""

[[extensions.targeting]]
target = "purchase.shipping-discount.run"
input_query = "src/run.graphql"
export = "run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/sd/new"
details = "/app/od/:id"
