api_version = "2024-07"

[[extensions]]
name = "Volume Discount"
description = "Buy more, discount more"
handle = "product-discount"
type = "function"

[[extensions.targeting]]
target = "purchase.product-discount.run"
input_query = "src/run.graphql"
export = "run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/vd/new"
details = "/app/vd/:id"
